# Generated by Django 5.2.13 on 2026-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('particulier', 'Particulier'), ('ong', 'ONG'), ('entreprise', 'Entreprise')])),
                ('nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('rccm', models.CharField(blank=True, null=True)),
                ('nif', models.CharField(blank=True, null=True)),
                ('agrement_ong', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
