# Generated by Django 5.2.13 on 2026-05-24 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(unique=True)),
                ('type_template', models.CharField(choices=[('particulier', 'Particulier'), ('ong', 'ONG'), ('entreprise', 'Entreprise')])),
                ('objet', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('validite', models.DateField()),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoye'), ('accepte', 'Accepté')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('qte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pu_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
            ],
        ),
    ]
