# Generated by Django 5.2.13 on 2026-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoye'), ('accepte', 'Accepté')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='type_template',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('ong', 'ONG'), ('entreprise', 'Entreprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='pu_ht',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
