# Generated by Django 5.2.13 on 2026-05-25 15:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_lignedevis_montant_ht_alter_devis_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='date',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='validite',
        ),
        migrations.AddField(
            model_name='devis',
            name='date_emission',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='date_validite',
            field=models.DateField(blank=True, help_text='Calculé automatiquement à la sauvegarde', null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='devise',
            field=models.CharField(choices=[('XAF', 'FCFA (XAF)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar ($)')], default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='devis',
            name='reference_appel_offre',
            field=models.CharField(blank=True, help_text="N° de l'Appel d'Offres du client", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='reference_projet',
            field=models.CharField(blank=True, help_text='Nom du projet ou code budgétaire', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='validite_jours',
            field=models.IntegerField(default=30, help_text="Durée de validité de l'offre en jours"),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='objet',
            field=models.CharField(help_text='Ex: Fourniture et installation de serveurs', max_length=255),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('negociation', 'En Négociation'), ('accepte', 'Accepté / Validé'), ('refuse', 'Refusé / Annulé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='devis',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='devis',
            name='type_template',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('ong', 'ONG'), ('entreprise', 'Entreprise / Grande Structure')], default='entreprise', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
