# Generated by Django 5.2.13 on 2026-06-15 07:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_remove_devis_date_remove_devis_validite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignedevis',
            options={'verbose_name': 'Ligne de devis', 'verbose_name_plural': 'Lignes de devis'},
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='description',
            field=models.TextField(blank=True, help_text='Détails ou spécifications techniques supplémentaires', null=True),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='remise_pourcentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remise en % sur cette ligne', max_digits=5),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(choices=[('U', 'Unité (U)'), ('ENS', 'Ensemble (ENS)'), ('FF', 'Forfait (FF)'), ('H', 'Heure (H)'), ('J', 'Jour (J)'), ('M', 'Mètre (m)'), ('M2', 'Mètre carré (m²)'), ('M3', 'Mètre cube (m³)'), ('KG', 'Kilogramme (kg)'), ('L', 'Litre (L)'), ('CJ', 'Configuration / Jour')], default='U', help_text='Unité de mesure', max_length=10),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='designation',
            field=models.CharField(help_text='Nom du produit ou du service', max_length=255),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='pu_ht',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix Unitaire HT'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='qte',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité'),
        ),
    ]
