# Generated by Django 5.2.13 on 2026-07-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_alter_lignedevis_options_lignedevis_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AddField(
            model_name='devis',
            name='domaine',
            field=models.CharField(choices=[('general', 'Général / Commerce'), ('btp', 'Bâtiment & Travaux Publics (BTP)'), ('it', 'Informatique & Télécoms (IT)'), ('service', 'Prestation de Services / Conseil')], default='general', max_length=20, verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(choices=[('U', 'Unité (U)'), ('ENS', 'Ensemble (ENS)'), ('FF', 'Forfait (FF)'), ('M', 'Mètre (m)'), ('M2', 'Mètre carré (m²)'), ('M3', 'Mètre cube (m³)'), ('KG', 'Kilogramme (kg)'), ('L', 'Litre (L)'), ('TONNE', 'Tonne (T)'), ('H', 'Heure (H)'), ('J', 'Jour (J)'), ('MOIS', 'Mois (M)'), ('CJ', 'Configuration / Jour')], default='U', help_text='Unité de mesure', max_length=10),
        ),
    ]
